language: java
jdk:
- oraclejdk7
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: TzdrBLhCxztHGpw/WLsxaAGmzAZDZGDx+XnLdqogv2iw4C69g04zryeR5qjkrgE8RQMhTKwW+VUMPKXdsVYBl5sW3odYQ5jEpESvQYmzNhHcIw26d4s5NLTaxi8WhTUJKDUdKKdMr9unQ4JfZa/80vXvxViq49sIkSFW8OCP6Fo=
  - secure: L0Jy139wWSBiQ7pu5H1KZchLPdSwU5PbfhqMcBP6n5rwIPNpBEK49zwZA/QHd5UiFV4zlvUT1umluyHtULxzKuwUGUHzWeA0UQ06e+URExHx1eVLehp0t7AuQKNEiV52uXQRIe+Bs31XAH5gUAUaD4flkfXBDpsCyMaL5mJvU5w=
  - secure: JN4JT2czgsPcDQsDUQ4gxVX+Pkc9HQHvDG3POR1sQgiCDpJa7evfn8bYUORpEwYXHCKW3+8EVJFCrobLcqzOuIlr84yBBzIXycqfiS6fyf4fLF1lMWc2ip7VSgAIje8TPM6nJO5m9B7ebFURRqujT75jsKmyR4Prh/hDP6vGCBA=
  - secure: O4nvKmaoGx+U5c1kkf8YvdqDmLCqhaCfmsNHsfwrmIWVRnrOfqu7PgKivXuEMq/sDKtPrOAHV+3736tVh4riKaa54bQ4YSR5ZvQW9m8RyNdYdXjWBz1wyFIFwHjuHNapHnATV7udksVa7cWXS+pcpetLa+Rx/ITjENYwCoTlW/M=
