language: java
jdk:
- oraclejdk7
sudo: false
script: gradle/buildViaTravis.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: INk2gUkERRJHUr5l2TxDwhqbcN9Axax4OgfOT7aellmeG7JGQdeI9LXp1kZPVU48u+2IdeXcBpN8ZZCKPOD6D3VxJWRTvLPcHTrZ2dsj8kdwqbfvtxL37QkPKmReB1n/wyGaE90KK6VWGZ1UeOBtdHg4AN/8K9yJWFBPa6kSSqI=
  - secure: dm6a3tpH0NzMGUELjLGUuXRBU52I/XWX6rkytkkgNJJFf5kzvFN5YB+10jlJVlzu9uLWOAZ75qGJmW77zCdNWROoyyvdvXzrazh70Cry69SGo3RicT6up/NA3AHqclXGKF42Pn3nYSgvsKMSxxaP/NNF1gm5e9Tl35WYtOqZXIk=
  - secure: JLDVCFwPrRL70OY0M0g2b+YVu3Ry7z2ZL5lA0+yRFsK5gSRaCPLzOTq5a4w6yrkc4VbTJnOA4IIpfgnyRuhh8o4v1rl2jEPydXeEN+Yrb+zJqCQAuOBzXSwJmjZECUV1VLqXJWYK5QsKv2XqRA3H9VTyi1kVoofdGh7fydk5gP8=
  - secure: BWZfl2zX+2lDDN388e8UNCxmuD12Ha8KH+/UW9B7DIgmM5q9ODSdYgIjugPXY2aKMxDpTvSTkx7zUDQtl9afXn6tN8vFcOvaduoj2SDdX5svTrpprTFdbE1TFnrrbDqkPvFsT/LBMJrQFDU0Cu/9CW6uSkMbZiDIe+7/Xbr8fMM=
